// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

public interface AlignmentMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assembly.AlignmentMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query_name = 1;</code>
   * @return The queryName.
   */
  java.lang.String getQueryName();
  /**
   * <code>string query_name = 1;</code>
   * @return The bytes for queryName.
   */
  com.google.protobuf.ByteString
      getQueryNameBytes();

  /**
   * <code>int32 query_length = 2;</code>
   * @return The queryLength.
   */
  int getQueryLength();

  /**
   * <code>int32 query_start = 3;</code>
   * @return The queryStart.
   */
  int getQueryStart();

  /**
   * <code>int32 query_end = 4;</code>
   * @return The queryEnd.
   */
  int getQueryEnd();

  /**
   * <code>bool strand = 5;</code>
   * @return The strand.
   */
  boolean getStrand();

  /**
   * <code>string target_name = 6;</code>
   * @return The targetName.
   */
  java.lang.String getTargetName();
  /**
   * <code>string target_name = 6;</code>
   * @return The bytes for targetName.
   */
  com.google.protobuf.ByteString
      getTargetNameBytes();

  /**
   * <code>int32 target_length = 7;</code>
   * @return The targetLength.
   */
  int getTargetLength();

  /**
   * <code>int32 target_start = 8;</code>
   * @return The targetStart.
   */
  int getTargetStart();

  /**
   * <code>int32 target_end = 9;</code>
   * @return The targetEnd.
   */
  int getTargetEnd();

  /**
   * <code>int32 quality = 10;</code>
   * @return The quality.
   */
  int getQuality();

  /**
   * <code>int32 score = 11;</code>
   * @return The score.
   */
  int getScore();
}
