// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

public final class AssemblyGuideProto {
  private AssemblyGuideProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assembly_AlignmentMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assembly_AlignmentMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assembly_RequestAssembly_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assembly_RequestAssembly_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assembly_ResponseAssembly_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assembly_ResponseAssembly_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025npgraph_service.proto\022\010assembly\"\346\001\n\014Al" +
      "ignmentMsg\022\022\n\nquery_name\030\001 \001(\t\022\024\n\014query_" +
      "length\030\002 \001(\005\022\023\n\013query_start\030\003 \001(\005\022\021\n\tque" +
      "ry_end\030\004 \001(\005\022\016\n\006strand\030\005 \001(\010\022\023\n\013target_n" +
      "ame\030\006 \001(\t\022\025\n\rtarget_length\030\007 \001(\005\022\024\n\014targ" +
      "et_start\030\010 \001(\005\022\022\n\ntarget_end\030\t \001(\005\022\017\n\007qu" +
      "ality\030\n \001(\005\022\r\n\005score\030\013 \001(\005\"M\n\017RequestAss" +
      "embly\022\017\n\007read_id\030\001 \001(\t\022)\n\thits_list\030\002 \003(" +
      "\0132\026.assembly.AlignmentMsg\"7\n\020ResponseAss" +
      "embly\022\017\n\007read_id\030\001 \001(\t\022\022\n\nusefulness\030\002 \001" +
      "(\0102c\n\rAssemblyGuide\022R\n\027GetAssemblyContri" +
      "bution\022\031.assembly.RequestAssembly\032\032.asse" +
      "mbly.ResponseAssembly\"\000B9\n\033org.rtassembl" +
      "y.npgraph.grpcB\022AssemblyGuideProtoP\001\242\002\003A" +
      "GPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assembly_AlignmentMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assembly_AlignmentMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assembly_AlignmentMsg_descriptor,
        new java.lang.String[] { "QueryName", "QueryLength", "QueryStart", "QueryEnd", "Strand", "TargetName", "TargetLength", "TargetStart", "TargetEnd", "Quality", "Score", });
    internal_static_assembly_RequestAssembly_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_assembly_RequestAssembly_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assembly_RequestAssembly_descriptor,
        new java.lang.String[] { "ReadId", "HitsList", });
    internal_static_assembly_ResponseAssembly_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_assembly_ResponseAssembly_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assembly_ResponseAssembly_descriptor,
        new java.lang.String[] { "ReadId", "Usefulness", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
