// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

public interface RequestAssemblyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assembly.RequestAssembly)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string read_id = 1;</code>
   * @return The readId.
   */
  java.lang.String getReadId();
  /**
   * <code>string read_id = 1;</code>
   * @return The bytes for readId.
   */
  com.google.protobuf.ByteString
      getReadIdBytes();

  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg> 
      getHitsListList();
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  org.rtassembly.npgraph.grpc.AlignmentMsg getHitsList(int index);
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  int getHitsListCount();
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  java.util.List<? extends org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder> 
      getHitsListOrBuilderList();
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder getHitsListOrBuilder(
      int index);
}
