// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

/**
 * <pre>
 * Client sent all hits from a chunk simultaneously
 * </pre>
 *
 * Protobuf type {@code assembly.RequestAssembly}
 */
public  final class RequestAssembly extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:assembly.RequestAssembly)
    RequestAssemblyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestAssembly.newBuilder() to construct.
  private RequestAssembly(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestAssembly() {
    readId_ = "";
    hitsList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestAssembly();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestAssembly(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            readId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              hitsList_ = new java.util.ArrayList<org.rtassembly.npgraph.grpc.AlignmentMsg>();
              mutable_bitField0_ |= 0x00000001;
            }
            hitsList_.add(
                input.readMessage(org.rtassembly.npgraph.grpc.AlignmentMsg.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        hitsList_ = java.util.Collections.unmodifiableList(hitsList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_RequestAssembly_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_RequestAssembly_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rtassembly.npgraph.grpc.RequestAssembly.class, org.rtassembly.npgraph.grpc.RequestAssembly.Builder.class);
  }

  public static final int READ_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object readId_;
  /**
   * <code>string read_id = 1;</code>
   * @return The readId.
   */
  public java.lang.String getReadId() {
    java.lang.Object ref = readId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readId_ = s;
      return s;
    }
  }
  /**
   * <code>string read_id = 1;</code>
   * @return The bytes for readId.
   */
  public com.google.protobuf.ByteString
      getReadIdBytes() {
    java.lang.Object ref = readId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HITS_LIST_FIELD_NUMBER = 2;
  private java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg> hitsList_;
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  public java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg> getHitsListList() {
    return hitsList_;
  }
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  public java.util.List<? extends org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder> 
      getHitsListOrBuilderList() {
    return hitsList_;
  }
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  public int getHitsListCount() {
    return hitsList_.size();
  }
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  public org.rtassembly.npgraph.grpc.AlignmentMsg getHitsList(int index) {
    return hitsList_.get(index);
  }
  /**
   * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
   */
  public org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder getHitsListOrBuilder(
      int index) {
    return hitsList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReadIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, readId_);
    }
    for (int i = 0; i < hitsList_.size(); i++) {
      output.writeMessage(2, hitsList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReadIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, readId_);
    }
    for (int i = 0; i < hitsList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, hitsList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rtassembly.npgraph.grpc.RequestAssembly)) {
      return super.equals(obj);
    }
    org.rtassembly.npgraph.grpc.RequestAssembly other = (org.rtassembly.npgraph.grpc.RequestAssembly) obj;

    if (!getReadId()
        .equals(other.getReadId())) return false;
    if (!getHitsListList()
        .equals(other.getHitsListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + READ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReadId().hashCode();
    if (getHitsListCount() > 0) {
      hash = (37 * hash) + HITS_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getHitsListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.RequestAssembly parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rtassembly.npgraph.grpc.RequestAssembly prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Client sent all hits from a chunk simultaneously
   * </pre>
   *
   * Protobuf type {@code assembly.RequestAssembly}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:assembly.RequestAssembly)
      org.rtassembly.npgraph.grpc.RequestAssemblyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_RequestAssembly_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_RequestAssembly_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rtassembly.npgraph.grpc.RequestAssembly.class, org.rtassembly.npgraph.grpc.RequestAssembly.Builder.class);
    }

    // Construct using org.rtassembly.npgraph.grpc.RequestAssembly.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHitsListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      readId_ = "";

      if (hitsListBuilder_ == null) {
        hitsList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        hitsListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_RequestAssembly_descriptor;
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.RequestAssembly getDefaultInstanceForType() {
      return org.rtassembly.npgraph.grpc.RequestAssembly.getDefaultInstance();
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.RequestAssembly build() {
      org.rtassembly.npgraph.grpc.RequestAssembly result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.RequestAssembly buildPartial() {
      org.rtassembly.npgraph.grpc.RequestAssembly result = new org.rtassembly.npgraph.grpc.RequestAssembly(this);
      int from_bitField0_ = bitField0_;
      result.readId_ = readId_;
      if (hitsListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          hitsList_ = java.util.Collections.unmodifiableList(hitsList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.hitsList_ = hitsList_;
      } else {
        result.hitsList_ = hitsListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rtassembly.npgraph.grpc.RequestAssembly) {
        return mergeFrom((org.rtassembly.npgraph.grpc.RequestAssembly)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rtassembly.npgraph.grpc.RequestAssembly other) {
      if (other == org.rtassembly.npgraph.grpc.RequestAssembly.getDefaultInstance()) return this;
      if (!other.getReadId().isEmpty()) {
        readId_ = other.readId_;
        onChanged();
      }
      if (hitsListBuilder_ == null) {
        if (!other.hitsList_.isEmpty()) {
          if (hitsList_.isEmpty()) {
            hitsList_ = other.hitsList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHitsListIsMutable();
            hitsList_.addAll(other.hitsList_);
          }
          onChanged();
        }
      } else {
        if (!other.hitsList_.isEmpty()) {
          if (hitsListBuilder_.isEmpty()) {
            hitsListBuilder_.dispose();
            hitsListBuilder_ = null;
            hitsList_ = other.hitsList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            hitsListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHitsListFieldBuilder() : null;
          } else {
            hitsListBuilder_.addAllMessages(other.hitsList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rtassembly.npgraph.grpc.RequestAssembly parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rtassembly.npgraph.grpc.RequestAssembly) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object readId_ = "";
    /**
     * <code>string read_id = 1;</code>
     * @return The readId.
     */
    public java.lang.String getReadId() {
      java.lang.Object ref = readId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string read_id = 1;</code>
     * @return The bytes for readId.
     */
    public com.google.protobuf.ByteString
        getReadIdBytes() {
      java.lang.Object ref = readId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string read_id = 1;</code>
     * @param value The readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      readId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string read_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadId() {
      
      readId_ = getDefaultInstance().getReadId();
      onChanged();
      return this;
    }
    /**
     * <code>string read_id = 1;</code>
     * @param value The bytes for readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      readId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg> hitsList_ =
      java.util.Collections.emptyList();
    private void ensureHitsListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hitsList_ = new java.util.ArrayList<org.rtassembly.npgraph.grpc.AlignmentMsg>(hitsList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.rtassembly.npgraph.grpc.AlignmentMsg, org.rtassembly.npgraph.grpc.AlignmentMsg.Builder, org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder> hitsListBuilder_;

    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg> getHitsListList() {
      if (hitsListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(hitsList_);
      } else {
        return hitsListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public int getHitsListCount() {
      if (hitsListBuilder_ == null) {
        return hitsList_.size();
      } else {
        return hitsListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public org.rtassembly.npgraph.grpc.AlignmentMsg getHitsList(int index) {
      if (hitsListBuilder_ == null) {
        return hitsList_.get(index);
      } else {
        return hitsListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder setHitsList(
        int index, org.rtassembly.npgraph.grpc.AlignmentMsg value) {
      if (hitsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitsListIsMutable();
        hitsList_.set(index, value);
        onChanged();
      } else {
        hitsListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder setHitsList(
        int index, org.rtassembly.npgraph.grpc.AlignmentMsg.Builder builderForValue) {
      if (hitsListBuilder_ == null) {
        ensureHitsListIsMutable();
        hitsList_.set(index, builderForValue.build());
        onChanged();
      } else {
        hitsListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder addHitsList(org.rtassembly.npgraph.grpc.AlignmentMsg value) {
      if (hitsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitsListIsMutable();
        hitsList_.add(value);
        onChanged();
      } else {
        hitsListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder addHitsList(
        int index, org.rtassembly.npgraph.grpc.AlignmentMsg value) {
      if (hitsListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHitsListIsMutable();
        hitsList_.add(index, value);
        onChanged();
      } else {
        hitsListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder addHitsList(
        org.rtassembly.npgraph.grpc.AlignmentMsg.Builder builderForValue) {
      if (hitsListBuilder_ == null) {
        ensureHitsListIsMutable();
        hitsList_.add(builderForValue.build());
        onChanged();
      } else {
        hitsListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder addHitsList(
        int index, org.rtassembly.npgraph.grpc.AlignmentMsg.Builder builderForValue) {
      if (hitsListBuilder_ == null) {
        ensureHitsListIsMutable();
        hitsList_.add(index, builderForValue.build());
        onChanged();
      } else {
        hitsListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder addAllHitsList(
        java.lang.Iterable<? extends org.rtassembly.npgraph.grpc.AlignmentMsg> values) {
      if (hitsListBuilder_ == null) {
        ensureHitsListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hitsList_);
        onChanged();
      } else {
        hitsListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder clearHitsList() {
      if (hitsListBuilder_ == null) {
        hitsList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        hitsListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public Builder removeHitsList(int index) {
      if (hitsListBuilder_ == null) {
        ensureHitsListIsMutable();
        hitsList_.remove(index);
        onChanged();
      } else {
        hitsListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public org.rtassembly.npgraph.grpc.AlignmentMsg.Builder getHitsListBuilder(
        int index) {
      return getHitsListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder getHitsListOrBuilder(
        int index) {
      if (hitsListBuilder_ == null) {
        return hitsList_.get(index);  } else {
        return hitsListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public java.util.List<? extends org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder> 
         getHitsListOrBuilderList() {
      if (hitsListBuilder_ != null) {
        return hitsListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(hitsList_);
      }
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public org.rtassembly.npgraph.grpc.AlignmentMsg.Builder addHitsListBuilder() {
      return getHitsListFieldBuilder().addBuilder(
          org.rtassembly.npgraph.grpc.AlignmentMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public org.rtassembly.npgraph.grpc.AlignmentMsg.Builder addHitsListBuilder(
        int index) {
      return getHitsListFieldBuilder().addBuilder(
          index, org.rtassembly.npgraph.grpc.AlignmentMsg.getDefaultInstance());
    }
    /**
     * <code>repeated .assembly.AlignmentMsg hits_list = 2;</code>
     */
    public java.util.List<org.rtassembly.npgraph.grpc.AlignmentMsg.Builder> 
         getHitsListBuilderList() {
      return getHitsListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.rtassembly.npgraph.grpc.AlignmentMsg, org.rtassembly.npgraph.grpc.AlignmentMsg.Builder, org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder> 
        getHitsListFieldBuilder() {
      if (hitsListBuilder_ == null) {
        hitsListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.rtassembly.npgraph.grpc.AlignmentMsg, org.rtassembly.npgraph.grpc.AlignmentMsg.Builder, org.rtassembly.npgraph.grpc.AlignmentMsgOrBuilder>(
                hitsList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        hitsList_ = null;
      }
      return hitsListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:assembly.RequestAssembly)
  }

  // @@protoc_insertion_point(class_scope:assembly.RequestAssembly)
  private static final org.rtassembly.npgraph.grpc.RequestAssembly DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rtassembly.npgraph.grpc.RequestAssembly();
  }

  public static org.rtassembly.npgraph.grpc.RequestAssembly getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestAssembly>
      PARSER = new com.google.protobuf.AbstractParser<RequestAssembly>() {
    @java.lang.Override
    public RequestAssembly parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestAssembly(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestAssembly> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestAssembly> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rtassembly.npgraph.grpc.RequestAssembly getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

