// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

/**
 * <pre>
 * Response from the assembly guide service: useful or not
 * </pre>
 *
 * Protobuf type {@code assembly.ResponseAssembly}
 */
public  final class ResponseAssembly extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:assembly.ResponseAssembly)
    ResponseAssemblyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseAssembly.newBuilder() to construct.
  private ResponseAssembly(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseAssembly() {
    readId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseAssembly();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseAssembly(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            readId_ = s;
            break;
          }
          case 16: {

            usefulness_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_ResponseAssembly_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_ResponseAssembly_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.rtassembly.npgraph.grpc.ResponseAssembly.class, org.rtassembly.npgraph.grpc.ResponseAssembly.Builder.class);
  }

  public static final int READ_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object readId_;
  /**
   * <code>string read_id = 1;</code>
   * @return The readId.
   */
  public java.lang.String getReadId() {
    java.lang.Object ref = readId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      readId_ = s;
      return s;
    }
  }
  /**
   * <code>string read_id = 1;</code>
   * @return The bytes for readId.
   */
  public com.google.protobuf.ByteString
      getReadIdBytes() {
    java.lang.Object ref = readId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      readId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USEFULNESS_FIELD_NUMBER = 2;
  private boolean usefulness_;
  /**
   * <code>bool usefulness = 2;</code>
   * @return The usefulness.
   */
  public boolean getUsefulness() {
    return usefulness_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReadIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, readId_);
    }
    if (usefulness_ != false) {
      output.writeBool(2, usefulness_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReadIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, readId_);
    }
    if (usefulness_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, usefulness_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.rtassembly.npgraph.grpc.ResponseAssembly)) {
      return super.equals(obj);
    }
    org.rtassembly.npgraph.grpc.ResponseAssembly other = (org.rtassembly.npgraph.grpc.ResponseAssembly) obj;

    if (!getReadId()
        .equals(other.getReadId())) return false;
    if (getUsefulness()
        != other.getUsefulness()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + READ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReadId().hashCode();
    hash = (37 * hash) + USEFULNESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getUsefulness());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.rtassembly.npgraph.grpc.ResponseAssembly parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.rtassembly.npgraph.grpc.ResponseAssembly prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response from the assembly guide service: useful or not
   * </pre>
   *
   * Protobuf type {@code assembly.ResponseAssembly}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:assembly.ResponseAssembly)
      org.rtassembly.npgraph.grpc.ResponseAssemblyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_ResponseAssembly_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_ResponseAssembly_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.rtassembly.npgraph.grpc.ResponseAssembly.class, org.rtassembly.npgraph.grpc.ResponseAssembly.Builder.class);
    }

    // Construct using org.rtassembly.npgraph.grpc.ResponseAssembly.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      readId_ = "";

      usefulness_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.rtassembly.npgraph.grpc.AssemblyGuideProto.internal_static_assembly_ResponseAssembly_descriptor;
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.ResponseAssembly getDefaultInstanceForType() {
      return org.rtassembly.npgraph.grpc.ResponseAssembly.getDefaultInstance();
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.ResponseAssembly build() {
      org.rtassembly.npgraph.grpc.ResponseAssembly result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.rtassembly.npgraph.grpc.ResponseAssembly buildPartial() {
      org.rtassembly.npgraph.grpc.ResponseAssembly result = new org.rtassembly.npgraph.grpc.ResponseAssembly(this);
      result.readId_ = readId_;
      result.usefulness_ = usefulness_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.rtassembly.npgraph.grpc.ResponseAssembly) {
        return mergeFrom((org.rtassembly.npgraph.grpc.ResponseAssembly)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.rtassembly.npgraph.grpc.ResponseAssembly other) {
      if (other == org.rtassembly.npgraph.grpc.ResponseAssembly.getDefaultInstance()) return this;
      if (!other.getReadId().isEmpty()) {
        readId_ = other.readId_;
        onChanged();
      }
      if (other.getUsefulness() != false) {
        setUsefulness(other.getUsefulness());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.rtassembly.npgraph.grpc.ResponseAssembly parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.rtassembly.npgraph.grpc.ResponseAssembly) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object readId_ = "";
    /**
     * <code>string read_id = 1;</code>
     * @return The readId.
     */
    public java.lang.String getReadId() {
      java.lang.Object ref = readId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string read_id = 1;</code>
     * @return The bytes for readId.
     */
    public com.google.protobuf.ByteString
        getReadIdBytes() {
      java.lang.Object ref = readId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string read_id = 1;</code>
     * @param value The readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      readId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string read_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadId() {
      
      readId_ = getDefaultInstance().getReadId();
      onChanged();
      return this;
    }
    /**
     * <code>string read_id = 1;</code>
     * @param value The bytes for readId to set.
     * @return This builder for chaining.
     */
    public Builder setReadIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      readId_ = value;
      onChanged();
      return this;
    }

    private boolean usefulness_ ;
    /**
     * <code>bool usefulness = 2;</code>
     * @return The usefulness.
     */
    public boolean getUsefulness() {
      return usefulness_;
    }
    /**
     * <code>bool usefulness = 2;</code>
     * @param value The usefulness to set.
     * @return This builder for chaining.
     */
    public Builder setUsefulness(boolean value) {
      
      usefulness_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool usefulness = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsefulness() {
      
      usefulness_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:assembly.ResponseAssembly)
  }

  // @@protoc_insertion_point(class_scope:assembly.ResponseAssembly)
  private static final org.rtassembly.npgraph.grpc.ResponseAssembly DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.rtassembly.npgraph.grpc.ResponseAssembly();
  }

  public static org.rtassembly.npgraph.grpc.ResponseAssembly getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseAssembly>
      PARSER = new com.google.protobuf.AbstractParser<ResponseAssembly>() {
    @java.lang.Override
    public ResponseAssembly parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseAssembly(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseAssembly> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseAssembly> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.rtassembly.npgraph.grpc.ResponseAssembly getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

