// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npgraph_service.proto

package org.rtassembly.npgraph.grpc;

public interface ResponseAssemblyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assembly.ResponseAssembly)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string read_id = 1;</code>
   * @return The readId.
   */
  java.lang.String getReadId();
  /**
   * <code>string read_id = 1;</code>
   * @return The bytes for readId.
   */
  com.google.protobuf.ByteString
      getReadIdBytes();

  /**
   * <code>bool usefulness = 2;</code>
   * @return The usefulness.
   */
  boolean getUsefulness();
}
