# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npgraph_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='npgraph_service.proto',
  package='assembly',
  syntax='proto3',
  serialized_options=b'\n\033org.rtassembly.npgraph.grpcB\022AssemblyGuideProtoP\001\242\002\003AGP',
  serialized_pb=b'\n\x15npgraph_service.proto\x12\x08\x61ssembly\"\xe6\x01\n\x0c\x41lignmentMsg\x12\x12\n\nquery_name\x18\x01 \x01(\t\x12\x14\n\x0cquery_length\x18\x02 \x01(\x05\x12\x13\n\x0bquery_start\x18\x03 \x01(\x05\x12\x11\n\tquery_end\x18\x04 \x01(\x05\x12\x0e\n\x06strand\x18\x05 \x01(\x08\x12\x13\n\x0btarget_name\x18\x06 \x01(\t\x12\x15\n\rtarget_length\x18\x07 \x01(\x05\x12\x14\n\x0ctarget_start\x18\x08 \x01(\x05\x12\x12\n\ntarget_end\x18\t \x01(\x05\x12\x0f\n\x07quality\x18\n \x01(\x05\x12\r\n\x05score\x18\x0b \x01(\x05\"M\n\x0fRequestAssembly\x12\x0f\n\x07read_id\x18\x01 \x01(\t\x12)\n\thits_list\x18\x02 \x03(\x0b\x32\x16.assembly.AlignmentMsg\"7\n\x10ResponseAssembly\x12\x0f\n\x07read_id\x18\x01 \x01(\t\x12\x12\n\nusefulness\x18\x02 \x01(\x08\x32\x63\n\rAssemblyGuide\x12R\n\x17GetAssemblyContribution\x12\x19.assembly.RequestAssembly\x1a\x1a.assembly.ResponseAssembly\"\x00\x42\x39\n\x1borg.rtassembly.npgraph.grpcB\x12\x41ssemblyGuideProtoP\x01\xa2\x02\x03\x41GPb\x06proto3'
)




_ALIGNMENTMSG = _descriptor.Descriptor(
  name='AlignmentMsg',
  full_name='assembly.AlignmentMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_name', full_name='assembly.AlignmentMsg.query_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_length', full_name='assembly.AlignmentMsg.query_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_start', full_name='assembly.AlignmentMsg.query_start', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query_end', full_name='assembly.AlignmentMsg.query_end', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strand', full_name='assembly.AlignmentMsg.strand', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_name', full_name='assembly.AlignmentMsg.target_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_length', full_name='assembly.AlignmentMsg.target_length', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_start', full_name='assembly.AlignmentMsg.target_start', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_end', full_name='assembly.AlignmentMsg.target_end', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quality', full_name='assembly.AlignmentMsg.quality', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='assembly.AlignmentMsg.score', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=266,
)


_REQUESTASSEMBLY = _descriptor.Descriptor(
  name='RequestAssembly',
  full_name='assembly.RequestAssembly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_id', full_name='assembly.RequestAssembly.read_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hits_list', full_name='assembly.RequestAssembly.hits_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=345,
)


_RESPONSEASSEMBLY = _descriptor.Descriptor(
  name='ResponseAssembly',
  full_name='assembly.ResponseAssembly',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_id', full_name='assembly.ResponseAssembly.read_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usefulness', full_name='assembly.ResponseAssembly.usefulness', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=402,
)

_REQUESTASSEMBLY.fields_by_name['hits_list'].message_type = _ALIGNMENTMSG
DESCRIPTOR.message_types_by_name['AlignmentMsg'] = _ALIGNMENTMSG
DESCRIPTOR.message_types_by_name['RequestAssembly'] = _REQUESTASSEMBLY
DESCRIPTOR.message_types_by_name['ResponseAssembly'] = _RESPONSEASSEMBLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlignmentMsg = _reflection.GeneratedProtocolMessageType('AlignmentMsg', (_message.Message,), {
  'DESCRIPTOR' : _ALIGNMENTMSG,
  '__module__' : 'npgraph_service_pb2'
  # @@protoc_insertion_point(class_scope:assembly.AlignmentMsg)
  })
_sym_db.RegisterMessage(AlignmentMsg)

RequestAssembly = _reflection.GeneratedProtocolMessageType('RequestAssembly', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTASSEMBLY,
  '__module__' : 'npgraph_service_pb2'
  # @@protoc_insertion_point(class_scope:assembly.RequestAssembly)
  })
_sym_db.RegisterMessage(RequestAssembly)

ResponseAssembly = _reflection.GeneratedProtocolMessageType('ResponseAssembly', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEASSEMBLY,
  '__module__' : 'npgraph_service_pb2'
  # @@protoc_insertion_point(class_scope:assembly.ResponseAssembly)
  })
_sym_db.RegisterMessage(ResponseAssembly)


DESCRIPTOR._options = None

_ASSEMBLYGUIDE = _descriptor.ServiceDescriptor(
  name='AssemblyGuide',
  full_name='assembly.AssemblyGuide',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=404,
  serialized_end=503,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAssemblyContribution',
    full_name='assembly.AssemblyGuide.GetAssemblyContribution',
    index=0,
    containing_service=None,
    input_type=_REQUESTASSEMBLY,
    output_type=_RESPONSEASSEMBLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASSEMBLYGUIDE)

DESCRIPTOR.services_by_name['AssemblyGuide'] = _ASSEMBLYGUIDE

# @@protoc_insertion_point(module_scope)
