# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import npgraph_service_pb2 as npgraph__service__pb2


class AssemblyGuideStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAssemblyContribution = channel.unary_unary(
                '/assembly.AssemblyGuide/GetAssemblyContribution',
                request_serializer=npgraph__service__pb2.RequestAssembly.SerializeToString,
                response_deserializer=npgraph__service__pb2.ResponseAssembly.FromString,
                )


class AssemblyGuideServicer(object):
    """Interface exported by the server.
    """

    def GetAssemblyContribution(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssemblyGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAssemblyContribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssemblyContribution,
                    request_deserializer=npgraph__service__pb2.RequestAssembly.FromString,
                    response_serializer=npgraph__service__pb2.ResponseAssembly.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assembly.AssemblyGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AssemblyGuide(object):
    """Interface exported by the server.
    """

    @staticmethod
    def GetAssemblyContribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/assembly.AssemblyGuide/GetAssemblyContribution',
            npgraph__service__pb2.RequestAssembly.SerializeToString,
            npgraph__service__pb2.ResponseAssembly.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
